### ISSUE TITLE
When trying to create iced_baseview::Settings, I get a Type Error (in https://github.com/BillyDM/iced-baseplug-examples )

### ISSUE THREAD

**Issue by zhavtom** [BillyDM/iced_baseview#18]
```
mismatched types

expected struct `baseview::window_open_options::WindowOpenOptions`, found struct `baseview::WindowOpenOptions`

note: perhaps two different versions of crate `baseview` are being used?rustc(E0308)
lib.rs(321, 21): expected struct `baseview::window_open_options::WindowOpenOptions`, found struct `baseview::WindowOpenOptions`
```
![image](https://user-images.githubusercontent.com/38828702/130037258-31d3cd0e-ee51-4e4b-85ee-0114b216a8ef.png)
I'm sorry, I'm still new to Rust, so I'm not sure what this means.

**Comment by BillyDM** [comment]
Oh, I thought I fixed this. I'll look into it later today. Thanks for letting me know!

**Comment by BillyDM** [comment]
It seems you are using baseplug. Could you make sure that the dependencies for `baseplug` and `baseview` match the ones listed in this example?

https://github.com/BillyDM/iced-baseplug-examples/blob/main/gain/Cargo.toml#L14

**Comment by zhavtom** [comment]
I haven't edited it at all since I downloaded it.

**Comment by zhavtom** [comment]
Oh, and I forgot some basic information.
OS: Windows 10 Pro 19042.1165
Rust: nightly-x86_64-pc-windows-msvc

**Comment by BillyDM** [comment]
> I haven't edited it at all since I downloaded it.

When did you download it? Could you please verify that the numbers after `rev` match the ones in the example Cargo.toml I linked above?

**Comment by BillyDM** [comment]
Oh, wait. My bad. The `baseview` version in `iced-baseplug-examples` was wrong. I updated it. Could you update/redownload the `iced-baseplug-examples` crate and see if it's working?

**Comment by zhavtom** [comment]
I downloaded and built it again, and it worked!

**Comment by zhavtom** [comment]
Thanks for the quick fix.
