### ISSUE TITLE
ModifiersChanged doesn't report the updated state of modifiers

### ISSUE THREAD

**Issue by Azorlogh** [BillyDM/iced_baseview#8]
The `ModifiersChanged` event doesn't correctly report the last modifier change, so if I press control, mods.control is false, but when I release it, mods.control will be true.

**Comment by BillyDM** [comment]
Okay, is the issue fixed for you now?

**Comment by Azorlogh** [comment]
I just realised there weren't any ModifiersChanged events to begin with haha.
But now the problem I'm mentionning is there.
I believe this is because baseview provides a KeyboardEvent who's modifiers doesn't contain the modifier key being pressed (which does reflects the underlying platform apis)
but meanwhile iced expects a ModifiersChanged event with the modifiers after the keypress so I think the pressed key needs to be manually added to the modifiers before emitting the IcedEvent

**Comment by BillyDM** [comment]
Okay, I'll look into it tomorrow.

**Comment by BillyDM** [comment]
The problem seems to be a platform-specific issue with `baseview`. It is working fine on Linux.

I made it so it keeps track of the modifiers manually for now as a temporary solution.

**Comment by Azorlogh** [comment]
Mmmh that's weird, I'm using Xorg on linux and too this is what I was seeing after printing the ModifiersChanged event:
```
Modifiers { shift: false, control: false, alt: false, logo: false } // start pressing control
Modifiers { shift: false, control: true, alt: false, logo: false } // stop pressing control
Modifiers { shift: false, control: false, alt: false, logo: false } // start pressing alt
Modifiers { shift: false, control: false, alt: true, logo: false } // stop pressing alt
```
After updating it seems to be working fine now :ok_hand: 
TYVM for this very useful crate :slightly_smiling_face:
